// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpFMwu0WHwkM6WkXLkWlfgLgS3eO7mmo',
    appId: '1:792521875878:web:d5af4678376d3a10562f67',
    messagingSenderId: '792521875878',
    projectId: 'chatapptask-3ff99',
    authDomain: 'chatapptask-3ff99.firebaseapp.com',
    storageBucket: 'chatapptask-3ff99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnVLxM1-oDKnZ9g6vg0wmoMgTC_8Vuog',
    appId: '1:792521875878:android:f986087fe9592a87562f67',
    messagingSenderId: '792521875878',
    projectId: 'chatapptask-3ff99',
    storageBucket: 'chatapptask-3ff99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1bt4Kk2tB5swx7MVpyVn0MoWwn2Cta8',
    appId: '1:792521875878:ios:4b388c8a0a5a9529562f67',
    messagingSenderId: '792521875878',
    projectId: 'chatapptask-3ff99',
    storageBucket: 'chatapptask-3ff99.appspot.com',
    iosBundleId: 'com.example.chatAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1bt4Kk2tB5swx7MVpyVn0MoWwn2Cta8',
    appId: '1:792521875878:ios:4b388c8a0a5a9529562f67',
    messagingSenderId: '792521875878',
    projectId: 'chatapptask-3ff99',
    storageBucket: 'chatapptask-3ff99.appspot.com',
    iosBundleId: 'com.example.chatAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIpFMwu0WHwkM6WkXLkWlfgLgS3eO7mmo',
    appId: '1:792521875878:web:ee88456be34b0548562f67',
    messagingSenderId: '792521875878',
    projectId: 'chatapptask-3ff99',
    authDomain: 'chatapptask-3ff99.firebaseapp.com',
    storageBucket: 'chatapptask-3ff99.appspot.com',
  );

}